### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[12, 1, 128, 128] to have 3 channels, but got 1 channels instead

### ISSUE THREAD

**Issue by s0966066980** [linxin0/SCPGabNet#4]
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[12, 1, 128, 128] to have 3 channels, but got 1 channels instead

I use own SIDD.h5 data

**Comment by linxin0** [comment]
I'm not sure of the reason/location of the error. Could you please train/test with the dataset we provided first? Make sure it's not an environmental or other issue before using your own dataset.

**Comment by linxin0** [comment]
Hi, thanks for your interest in our work! I'm not sure of the reason/location of the error. Could you please train/test with the dataset we provided first? Make sure it's not an environmental or other issue before using your own dataset.

**Comment by s0966066980** [comment]
Thank you for your reply, but I can't use the data you provided(baidu). Is there any other download space? Or can I ask you how to make your own dataset?

**Comment by linxin0** [comment]
Oh, sorry. I will upload the datasets to Huggingface these days when I free. 
Make the dataset: Choose the first half of the noisy image and the last half of the clean image to concat, i.e., 6 channels. This ensures that the images input to the generator are unpaired. Besides, we will also provide the code under the BasicSR framework in the future (this is a journal work in progress).
